{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE PolyKinds #-}
-- Derived from OpenAPI spec
module Stripe.Types.Lens where

-- TODO all of this needs to be qualified to account for generated output causing conflicts
import Control.Lens.TH
import qualified Stripe.Types as Gen

makeFields ''Gen.Account
makeFields ''Gen.AccountBrandingSettings
makeFields ''Gen.AccountBusinessProfile
makeFields ''Gen.AccountCapabilities
makeFields ''Gen.AccountCapabilityRequirements
makeFields ''Gen.AccountCardPaymentsSettings
makeFields ''Gen.AccountDashboardSettings
makeFields ''Gen.AccountDeclineChargeOn
makeFields ''Gen.AccountLink
makeFields ''Gen.AccountPaymentsSettings
makeFields ''Gen.AccountPayoutSettings
makeFields ''Gen.AccountRequirements
makeFields ''Gen.AccountSettings
makeFields ''Gen.AccountTosAcceptance
makeFields ''Gen.Address
makeFields ''Gen.AlipayAccount
makeFields ''Gen.ApiErrors
makeFields ''Gen.ApplePayDomain
makeFields ''Gen.Application
makeFields ''Gen.ApplicationFee
makeFields ''Gen.Balance
makeFields ''Gen.BalanceAmount
makeFields ''Gen.BalanceAmountBySourceType
makeFields ''Gen.BalanceTransaction
makeFields ''Gen.BankAccount
makeFields ''Gen.BillingDetails
makeFields ''Gen.BitcoinReceiver
makeFields ''Gen.BitcoinTransaction
makeFields ''Gen.Capability
makeFields ''Gen.Card
makeFields ''Gen.Charge
makeFields ''Gen.ChargeFraudDetails
makeFields ''Gen.ChargeOutcome
makeFields ''Gen.ChargeTransferData
makeFields ''Gen.CheckoutSessionCustomDisplayItemDescription
makeFields ''Gen.CheckoutSessionDisplayItem
makeFields ''Gen.ConnectCollectionTransfer
makeFields ''Gen.CountrySpec
makeFields ''Gen.CountrySpecVerificationFieldDetails
makeFields ''Gen.CountrySpecVerificationFields
makeFields ''Gen.Coupon
makeFields ''Gen.CreditNote
makeFields ''Gen.Customer
makeFields ''Gen.CustomerBalanceTransaction
makeFields ''Gen.DeletedAccount
makeFields ''Gen.DeletedAlipayAccount
makeFields ''Gen.DeletedApplePayDomain
makeFields ''Gen.DeletedBankAccount
makeFields ''Gen.DeletedBitcoinReceiver
makeFields ''Gen.DeletedCard
makeFields ''Gen.DeletedCoupon
makeFields ''Gen.DeletedCustomer
makeFields ''Gen.DeletedDiscount
makeFields ''Gen.DeletedExternalAccount
makeFields ''Gen.DeletedInvoice
makeFields ''Gen.DeletedInvoiceitem
makeFields ''Gen.DeletedPaymentSource
makeFields ''Gen.DeletedPerson
makeFields ''Gen.DeletedPlan
makeFields ''Gen.DeletedProduct
makeFields ''Gen.DeletedRecipient
makeFields ''Gen.DeletedSku
makeFields ''Gen.DeletedSubscriptionItem
makeFields ''Gen.DeletedTaxId
makeFields ''Gen.DeletedWebhookEndpoint
makeFields ''Gen.DeliveryEstimate
makeFields ''Gen.Discount
makeFields ''Gen.Dispute
makeFields ''Gen.DisputeEvidence
makeFields ''Gen.DisputeEvidenceDetails
makeFields ''Gen.EphemeralKey
makeFields ''Gen.Error
makeFields ''Gen.Event
makeFields ''Gen.ExchangeRate
makeFields ''Gen.ExternalAccount
makeFields ''Gen.Fee
makeFields ''Gen.FeeRefund
makeFields ''Gen.File
makeFields ''Gen.FileLink
makeFields ''Gen.FinancialReportingFinanceReportRunRunParameters
makeFields ''Gen.Inventory
makeFields ''Gen.Invoice
makeFields ''Gen.InvoiceItemThresholdReason
makeFields ''Gen.InvoiceLineItemPeriod
makeFields ''Gen.InvoiceSettingCustomField
makeFields ''Gen.InvoiceSettingCustomerSetting
makeFields ''Gen.InvoiceSettingSubscriptionScheduleSetting
makeFields ''Gen.InvoiceTaxAmount
makeFields ''Gen.InvoiceThresholdReason
makeFields ''Gen.Invoiceitem
makeFields ''Gen.InvoicesResourceInvoiceTaxId
makeFields ''Gen.InvoicesStatusTransitions
makeFields ''Gen.IssuerFraudRecord
makeFields ''Gen.IssuingAuthorizationMerchantData
makeFields ''Gen.IssuingAuthorizationRequest
makeFields ''Gen.IssuingAuthorizationVerificationData
makeFields ''Gen.IssuingCardAuthorizationControls
makeFields ''Gen.IssuingCardPin
makeFields ''Gen.IssuingCardShipping
makeFields ''Gen.IssuingCardSpendingLimit
makeFields ''Gen.IssuingCardholderAddress
makeFields ''Gen.IssuingCardholderAuthorizationControls
makeFields ''Gen.IssuingCardholderSpendingLimit
makeFields ''Gen.IssuingDisputeEvidence
makeFields ''Gen.IssuingDisputeFraudulentEvidence
makeFields ''Gen.IssuingDisputeOtherEvidence
makeFields ''Gen.LegalEntityCompany
makeFields ''Gen.LegalEntityCompanyVerification
makeFields ''Gen.LegalEntityCompanyVerificationDocument
makeFields ''Gen.LegalEntityDob
makeFields ''Gen.LegalEntityJapanAddress
makeFields ''Gen.LegalEntityPersonVerification
makeFields ''Gen.LegalEntityPersonVerificationDocument
makeFields ''Gen.LightAccountLogout
makeFields ''Gen.LineItem
makeFields ''Gen.LoginLink
makeFields ''Gen.NotificationEventData
makeFields ''Gen.NotificationEventRequest
makeFields ''Gen.Order
makeFields ''Gen.OrderItem
makeFields ''Gen.OrderReturn
makeFields ''Gen.PackageDimensions
makeFields ''Gen.PaymentIntent
makeFields ''Gen.PaymentIntentNextAction
makeFields ''Gen.PaymentIntentNextActionRedirectToUrl
makeFields ''Gen.PaymentIntentPaymentMethodOptions
makeFields ''Gen.PaymentIntentPaymentMethodOptionsCard
makeFields ''Gen.PaymentMethod
makeFields ''Gen.PaymentMethodCard
makeFields ''Gen.PaymentMethodCardChecks
makeFields ''Gen.PaymentMethodCardGeneratedCard
makeFields ''Gen.PaymentMethodCardPresent
makeFields ''Gen.PaymentMethodCardWallet
makeFields ''Gen.PaymentMethodCardWalletAmexExpressCheckout
makeFields ''Gen.PaymentMethodCardWalletApplePay
makeFields ''Gen.PaymentMethodCardWalletGooglePay
makeFields ''Gen.PaymentMethodCardWalletMasterpass
makeFields ''Gen.PaymentMethodCardWalletSamsungPay
makeFields ''Gen.PaymentMethodCardWalletVisaCheckout
makeFields ''Gen.PaymentMethodDetails
makeFields ''Gen.PaymentMethodDetailsAchCreditTransfer
makeFields ''Gen.PaymentMethodDetailsAchDebit
makeFields ''Gen.PaymentMethodDetailsAlipay
makeFields ''Gen.PaymentMethodDetailsBancontact
makeFields ''Gen.PaymentMethodDetailsCard
makeFields ''Gen.PaymentMethodDetailsCardChecks
makeFields ''Gen.PaymentMethodDetailsCardPresent
makeFields ''Gen.PaymentMethodDetailsCardPresentReceipt
makeFields ''Gen.PaymentMethodDetailsCardWallet
makeFields ''Gen.PaymentMethodDetailsCardWalletAmexExpressCheckout
makeFields ''Gen.PaymentMethodDetailsCardWalletApplePay
makeFields ''Gen.PaymentMethodDetailsCardWalletGooglePay
makeFields ''Gen.PaymentMethodDetailsCardWalletMasterpass
makeFields ''Gen.PaymentMethodDetailsCardWalletSamsungPay
makeFields ''Gen.PaymentMethodDetailsCardWalletVisaCheckout
makeFields ''Gen.PaymentMethodDetailsEps
makeFields ''Gen.PaymentMethodDetailsGiropay
makeFields ''Gen.PaymentMethodDetailsIdeal
makeFields ''Gen.PaymentMethodDetailsKlarna
makeFields ''Gen.PaymentMethodDetailsMultibanco
makeFields ''Gen.PaymentMethodDetailsP24
makeFields ''Gen.PaymentMethodDetailsSepaDebit
makeFields ''Gen.PaymentMethodDetailsSofort
makeFields ''Gen.PaymentMethodDetailsStripeAccount
makeFields ''Gen.PaymentMethodDetailsWechat
makeFields ''Gen.PaymentSource
makeFields ''Gen.Payout
makeFields ''Gen.Period
makeFields ''Gen.Person
makeFields ''Gen.PersonRelationship
makeFields ''Gen.PersonRequirements
makeFields ''Gen.Plan
makeFields ''Gen.PlanTier
makeFields ''Gen.PlatformTaxFee
makeFields ''Gen.Product
makeFields ''Gen.RadarReviewResourceLocation
makeFields ''Gen.RadarReviewResourceSession
makeFields ''Gen.Recipient
makeFields ''Gen.Refund
makeFields ''Gen.ReserveTransaction
makeFields ''Gen.Review
makeFields ''Gen.Rule
makeFields ''Gen.ScheduledQueryRun
makeFields ''Gen.SetupIntent
makeFields ''Gen.SetupIntentNextAction
makeFields ''Gen.SetupIntentNextActionRedirectToUrl
makeFields ''Gen.SetupIntentPaymentMethodOptions
makeFields ''Gen.SetupIntentPaymentMethodOptionsCard
makeFields ''Gen.Shipping
makeFields ''Gen.ShippingMethod
makeFields ''Gen.SigmaScheduledQueryRunError
makeFields ''Gen.Sku
makeFields ''Gen.Source
makeFields ''Gen.SourceCodeVerificationFlow
makeFields ''Gen.SourceMandateNotification
makeFields ''Gen.SourceMandateNotificationBacsDebitData
makeFields ''Gen.SourceMandateNotificationSepaDebitData
makeFields ''Gen.SourceOrder
makeFields ''Gen.SourceOrderItem
makeFields ''Gen.SourceOwner
makeFields ''Gen.SourceReceiverFlow
makeFields ''Gen.SourceRedirectFlow
makeFields ''Gen.SourceTransaction
makeFields ''Gen.SourceTransactionAchCreditTransferData
makeFields ''Gen.SourceTransactionChfCreditTransferData
makeFields ''Gen.SourceTransactionGbpCreditTransferData
makeFields ''Gen.SourceTransactionPaperCheckData
makeFields ''Gen.SourceTransactionSepaCreditTransferData
makeFields ''Gen.SourceTypeAchCreditTransfer
makeFields ''Gen.SourceTypeAchDebit
makeFields ''Gen.SourceTypeAlipay
makeFields ''Gen.SourceTypeBancontact
makeFields ''Gen.SourceTypeCard
makeFields ''Gen.SourceTypeCardPresent
makeFields ''Gen.SourceTypeEps
makeFields ''Gen.SourceTypeGiropay
makeFields ''Gen.SourceTypeIdeal
makeFields ''Gen.SourceTypeKlarna
makeFields ''Gen.SourceTypeMultibanco
makeFields ''Gen.SourceTypeP24
makeFields ''Gen.SourceTypeSepaDebit
makeFields ''Gen.SourceTypeSofort
makeFields ''Gen.SourceTypeThreeDSecure
makeFields ''Gen.SourceTypeWechat
makeFields ''Gen.StatusTransitions
makeFields ''Gen.Subscription
makeFields ''Gen.SubscriptionBillingThresholds
makeFields ''Gen.SubscriptionItem
makeFields ''Gen.SubscriptionItemBillingThresholds
makeFields ''Gen.SubscriptionSchedule
makeFields ''Gen.SubscriptionScheduleConfigurationItem
makeFields ''Gen.SubscriptionScheduleCurrentPhase
makeFields ''Gen.SubscriptionSchedulePhaseConfiguration
makeFields ''Gen.SubscriptionScheduleRenewalInterval
makeFields ''Gen.TaxId
makeFields ''Gen.TaxIdVerification
makeFields ''Gen.TaxInfo
makeFields ''Gen.TaxInfoVerification
makeFields ''Gen.TaxRate
makeFields ''Gen.ThreeDSecure
makeFields ''Gen.ThreeDSecureDetails
makeFields ''Gen.ThreeDSecureUsage
makeFields ''Gen.Token
makeFields ''Gen.Topup
makeFields ''Gen.Transfer
makeFields ''Gen.TransferData
makeFields ''Gen.TransferReversal
makeFields ''Gen.TransferSchedule
makeFields ''Gen.TransformUsage
makeFields ''Gen.UsageRecord
makeFields ''Gen.UsageRecordSummary
makeFields ''Gen.WebhookEndpoint
